### PR TITLE
Don't redefine #method_missing

### PR DESCRIPTION
**Pull request by ZJvandeWeg**
Given its defined already: https://github.com/exAspArk/batch-loader/blob/master/lib/batch_loader.rb#L60

### CODE REVIEW

**Comment by ZJvandeWeg** [comment]
@exAspArk This patch I'm not 100% sure about, although it seems to be correct. Please let me know if my assumptions are right.

**Comment by ZJvandeWeg** [comment]
Added a changelog entry that I forgot.

**Comment by exAspArk** [comment]
Hey @ZJvandeWeg,

Thanks for the PR! I didn't include `method_missing` to the list because I'd like to keep it "replacable". To demonstrate what I mean, I added `User#method_missing`:

https://github.com/exAspArk/batch-loader/blob/7be21207ae2fefa27fb72c7bcd416ecce4e6f8b0/spec/fixtures/models.rb#L70-L72

And wrote the following test, which passes:

https://github.com/exAspArk/batch-loader/blob/7be21207ae2fefa27fb72c7bcd416ecce4e6f8b0/spec/batch_loader_spec.rb#L136-L146

The difference, however, is noticeable when I add `puts "DELEGATING"` to the `BatchLoader#method_missing`:

https://github.com/exAspArk/batch-loader/blob/7be21207ae2fefa27fb72c7bcd416ecce4e6f8b0/lib/batch_loader.rb#L60-L63

---

So, when I run the test w/o `method_missing` in the list, it prints out `DELEGATING` just once:
* calls `BatchLoader#method_missing` when I call `batch_loader.id`
* calls `User#method_missing` when I call `batch_loader.from_method_missing`

When I add `method_missing` to the list, it prints out `DELEGATING` twice:
* calls `BatchLoader#method_missing` when I call `batch_loader.id`
* calls `BatchLoader#method_missing` which delegates the call to the `User#method_missing` when I call `batch_loader.from_method_missing`

As you can see, excluding `method_missing` from the list allows avoiding delegating the method once the object was loaded. So, `BatchLoader#method_missing` is no longer a "proxy" method, which can prevent adding an extra performance penalty (for example, in this [issue](https://github.com/exAspArk/batch-loader/issues/2)).

**Comment by exAspArk** [comment]
@ZJvandeWeg closing the PR. Thanks again for contributing!

This `method_missing` and auto-syncing part is very confusing and complicated 😞

**Pull request closed without merging**
