### PR TITLE
Fix arity bug in respond_to? method

### PR DESCRIPTION
**Pull request by ZJvandeWeg**

### CODE REVIEW

**Comment by ZJvandeWeg** [comment]
@exAspArk It seemed not really needed to add a test. Please let me know what else you might need before merging/

**Comment by exAspArk** [comment]
@ZJvandeWeg looks great! Thank you! 🙌 

Since you dig into the source code, may I ask you a question: How do you use the gem? With GraphQL, RESTful API or anything else? 

In the version `1.x`, I decided to try the "magical" automatic syncing which potentially makes it easier to use BatchLoader without GraphQL:

> When we call any method on the lazy object, it'll be automatically loaded 

Because of this, the source code looks a bit complicated (compared to the [code](https://github.com/exAspArk/batch-loader/blob/0.x/lib/batch_loader.rb) in `0.x` branch) and leads to bugs like this one. I'm thinking whether the automatic loading worth it in general or not. Will be happy to hear your opinion.

**Comment by ZJvandeWeg** [comment]
@exAspArk I'm investigating if we, GitLab, can use it for another datasource. Our backend for git is called [Gitaly](https://gitlab.com/gitlab-org/gitaly), and like with databases, it doesn't have a magic solution for n + 1 queries on it.

On the magic loading, I kinda like it, but it was confusing at first to get started with it. And like you said, the code needed a few times reading and byebugging through it before I fully understood what was going on and why. I also worry a bit about the adoption, given the lazy loading has a few gotchas and the API.

Other than that, I'll update you in a week or so. 😄

**Comment by exAspArk** [comment]
@ZJvandeWeg thanks a lot for the feedback! Looking forward to hearing from you 😸

**Comment by ZJvandeWeg** [comment]
@exAspArk Sorry, I forgot to give extra feedback. We've now merged the first merge request using `batch-loader`: specifically on https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/15370/diffs#f34dbf3de4996b6652de2cbafe00a9a79e516365_79_79

If you have any feedback, please let me know. I've one minor question, on which I'll open an issue.

**Comment by exAspArk** [comment]
@ZJvandeWeg wow, thank you! That's awesome! 💥

**Pull request merged**
